const all = {
  name: "Bill Gates",
  full_name: "William Henry Bill Gates",
  address: "Seattle, Washington, U.S.A.",
  birth_date: "October 28, 1955",
  wikiLink: "https://en.wikipedia.org/wiki/Bill_Gates",
  imgLink: "https://wallpapercave.com/wp/aPjOydl.jpg",
  nameColor: "white",
  namePostion: "bottom",
  backImg: "https://wallpaperaccess.com/full/334662.jpg",
  data: [
    [
      "BIRTH",
      'Gates was born in Seattle, Washington, on October 28, 1955. He is the son of William H. Gates Sr.[c] (b. 1925) and Mary Maxwell Gates (1929�1994). His ancestry includes English, German, and Irish/Scots-Irish.His father was a prominent lawyer, and his mother served on the board of directors for First Interstate BancSystem and the United Way of America.Gates\' maternal grandfather was J. W. Maxwell, a national bank president. Gates has an older sister Kristi (Kristianne) and a younger sister Libby.[citation needed] He is the fourth of his name in his family but is known as William Gates III or "Trey" (i.e., three) because his father had the "II" suffix. The family lived in the Sand Point area of Seattle in a home that was damaged by a rare tornado when Gates was seven years old.',
    ],
    [
      "Early career",
      "Gates wrote his first software program at the age of 13. In high school he helped form a group of programmers who computerized their school's payroll system and founded Traf-O-Data, a company that sold traffic-counting systems to local governments. In 1975 Gates, then a sophomore at Harvard University, joined his hometown friend Paul G. Allen to develop software for the first microcomputers. They began by adapting BASIC, a popular programming language used on large computers, for use on microcomputers. With the success of this project, Gates left Harvard during his junior year and, with Allen, formed Microsoft. Gates's sway over the infant microcomputer industry greatly increased when Microsoft licensed an operating system called MS-DOS to International Business Machines Corporations then the world's biggest computer supplier and industry pacesetter's for use on its first microcomputer, the IBM PC (personal computer). After the machine's release in 1981, IBM quickly set the technical standard for the PC industry, and MS-DOS likewise pushed out competing operating systems. While Microsoft�s independence strained relations with IBM, Gates deftly manipulated the larger company so that it became permanently dependent on him for crucial software. Makers of IBM-compatible PCs, or clones, also turned to Microsoft for their basic software. By the start of the 1990s he had become the PC industry's ultimate kingmaker.Largely on the strength of Microsoft's success, Gates amassed a huge paper fortune as the company'ss largest individual shareholder. He became a paper billionaire in 1986, and within a decade his net worth had reached into the tens of billions of dollars making him by some estimates the world's richest private individual. With few interests beyond software and the potential of information technology, Gates at first preferred to stay out of the public eye, handling civic and philanthropic affairs indirectly through one of his foundations.",
    ],
    [
      "PROFESSIONAL CAREER",
      'Bill Gates met Steve Ballmer whom would soon join Gates in his venture to start his own company, Microsoft. This all started when Paul Allen, Bill\'s former school mate moved to Boston from Seattle for a job. Paul Allen picked up a magazine at Harvard Square which read, "World\'s First Minicomputer Kit To Rival Commercial Models" to Bill Gates and Paul Allen this was the moment they had been waiting for, the dawn of personal computer had begun. Ed Roberts who ran this phenomenal product was looking for someone to do further programming to it. Bill Gates and Allen Paul soon took on this task and this partnership with Ed Roberts eventually led to the first product made by Microsoft the Altair BASIC. "Microsoft" was created in 1976 Altair BASIC was an programming language which ran on the MITS Altair 8800. Gates due to the success of Altair BASIC decided to drop out of Harvard and never returned to complete his studies. Microsoft was located in Albuquerque from 1976 to 1979. In 1979 they relocated their location to Bellevue Washington on January,1,1979.           Microsoft began to expand and specialize in languages such as Basic,Cobol,Fortan,and Pascal. With this expansion and Microsoft having hit the one million dollar profit margin mark, it was a matter of time until a big-shot computer creative company came knocking at their door. That company was IBM. The partnership IBM and Microsoft developed was a pivotal role which defined technology, to what it has become today. It established what Gates had predicted, every home in America would have one computer per household. IBM wanted an operating system for their new line of personal computers. Bill Gates bought an operating system in which he renamed, MS-DOS for IBM. He received profit from IBM for every MS-DOS product made, as IBM didn\'t own the licensing fee, and Gates refused to give it to them.',
    ],
    [
      "REWARDS AND RECOGNITION",
      'Time magazine named Gates one of the 100 people who most influenced the 20th century, as well as one of the 100 most influential people of 2004, 2005, and 2006.                                Gates was listed in the Sunday Times power list in 1999, named CEO of the year by Chief Executive Officers magazine in 1994, ranked number one in the "Top 50 Cyber Elite" by Time in 1998, ranked number two in the Upside Elite 100 in 1999, and was included in The Guardian as one of the "Top 100 influential people in media" in 2001.          Gates was elected Member of the US National Academy of Engineering in 1996 "for contributions to the founding and development of personal computing".  He was named Honorary Member of the American Library Association in 1998.                       He was elected a foreign member of the Chinese Academy of Engineering in 2017.                    According to Forbes, Gates was ranked as the fourth most powerful person in the world in 2012, up from fifth in 2011.                                    In 1994, he was honored as the 20th Distinguished Fellow of the British Computer Society(DFBCS).In 1999, Gates received New York Institute of Technology\'s President\'s Medal.He was also made an honorary trustee of Peking University in 2007.Gates was made an Honorary Knight Commander of the Order of the British Empire (KBE) by Queen Elizabeth II in 2005.                              In November 2006, he was awarded the Placard of the Order of the Aztec Eagle, together with his wife Melinda who was awarded the Insignia of the same order, both for their philanthropic work around the world in the areas of health and education, particularly in Mexico, and specifically in the program "Un pa�s de lectores".                    Gates received the 2010 Bower Award for Business Leadership from The Franklin Institute for his achievements at Microsoft and his philanthropic work.                                               Also in 2010, he was honored with the Silver Buffalo Award by the Boy Scouts of America, its highest award for adults, for his service to youth.In 2002, Bill and Melinda Gates received the Jefferson Award for Greatest Public Service Benefiting the Disadvantaged.                      He was given the 2006 James C.Morgan Global Humanitarian Award from the Tech Awards.          In 2015 Gates, along with his wife Melinda, received the Padma Bhushan, India\'s third-highest civilian award for their social work in the country.Barack Obama honored Bill and Melinda Gates with the Presidential Medal of Freedom for their philanthropic efforts in 2016, and Fran�ois Hollande awarded Bill and Melinda in the following year with France\'s highest national order � as Commander of the Legion of Honour for their charity efforts.',
    ],
  ],
};
