const all = {
  name: "Elon Musk",
  full_name: "Elon Reeve Musk",
  address: "Pretoria, Transvaal, South Africa",
  birth_date: "June 28, 1971",
  wikiLink: "https://en.wikipedia.org/wiki/Elon_Musk",
  imgLink: "https://wallpapercave.com/wp/wp2048432.jpg",
  nameColor: "black",
  namePostion: "middle",
  backImg:
    "https://image.slidesharecdn.com/spacex-170316183139/95/space-x-1-638.jpg?cb=1489689194",
  data: [
    [
      "BIRTH",
      "Elon Musk was born on June 28, 1971, in Pretoria, Transvaal, South Africa,the son of Maye Musk, a model and dietitian from Regina, Saskatchewan, Canada,and Errol Musk, a South African electromechanical engineer, pilot, and sailor. He has a younger brother, Kimbal (born 1972), and a younger sister, Tosca. His maternal grandfather, Dr. Joshua Haldeman, was an American-born Canadian. His paternal grandmother was British, and he also has Pennsylvania Dutch ancestry.After his parents divorced in 1980, Musk lived mostly with his father in the suburbs of Pretoria, a choice he made two years after his parents separated but which he subsequently regretted.                                              During his childhood, Musk was an avid reader. At the age of 10, he developed an interest in computing while using the Commodore VIC-20.He taught himself computer programming and, by the age of 12, sold the code of a BASIC-based video game he created called Blastar to PC and Office Technology magazine for approximately $500.",
    ],
    [
      "Education",
      "While awaiting Canadian documentation, Musk attended the University of Pretoria for five months.Once in Canada, Musk entered Queen's University in 1989, avoiding mandatory service in the South African military.He left in 1992 to study business and physics at the University of Pennsylvania; he graduated with a Bachelor of Science degree in economics and a Bachelor of Arts degree in physics.                             In 1994, Musk held two internships in Silicon Valley during the summer: at an energy storage start-up called Pinnacle Research Institute, which researched electrolytic ultracapacitors for energy storage, and at the Palo Alto-based start-up Rocket Science Games. Bruce Leak, the former lead engineer behind Apple�s QuickTime who had hired Musk, noted: �He had boundless energy. Kids these days have no idea about hardware or how stuff works, but he had a PC hacker background and was not afraid to just go figure things out.           In 1995, Musk commenced a PhD in energy physics/materials science at Stanford University in California. Eager to pursue opportunities in the Internet boom, however, he dropped out after just two days to launch his first company, Zip2 Corporation.",
    ],
    [
      "Zip2",
      "In 1995, Musk and his brother, Kimbal, started Zip2, a web software company, with money raised from a small group of angel investors.The company developed and marketed an internet city guide for the newspaper publishing industry, with maps, directions and yellow pages, with the vector graphics mapping and direction code being implemented by Musk in Java. Musk obtained contracts with The New York Times and the Chicago Tribune, and persuaded the board of directors to abandon plans for a merger with CitySearch. Musk's attempts to become CEO were thwarted by the board. Compaq acquired Zip2 for US$307 million in cash in February 1999. Musk received US$22 million for his 7 percent share from the sale.",
    ],
    [
      "X.com and PayPal",
      "In March 1999, Musk co-founded X.com, an online financial services and e-mail payment company, with US$10 million from the sale of Zip2. One year later, the company merged with Confinity, which had a money-transfer service called PayPal. The merged company focused on the PayPal service and was renamed PayPal in 2001. Musk was ousted in October 2000 from his role as CEO (although he remained on the board) due to disagreements with other company executives over his desire to move PayPal's Unix-based infrastructure to Microsoft Windows.In October 2002, PayPal was acquired by eBay for US$1.5 billion in stock, of which Musk received US$165 million. Before its sale, Musk, who was the company's largest shareholder, owned 11.7% of PayPal's shares.                                        In July 2017, Musk purchased the domain X.com from PayPal for an undisclosed amount, stating that it has sentimental value to him.",
    ],
    [
      "SpaceX",
      "In 2001, Musk conceived Mars Oasis, a project to land a miniature experimental greenhouse on Mars, containing food crops growing on Martian regolith, in an attempt to reawaken public interest in space exploration. In October 2001, Musk traveled to Moscow with Jim Cantrell (an aerospace supplies fixer), and Adeo Ressi (his best friend from college), to buy refurbished Dnepr Intercontinental ballistic missiles (ICBMs) that could send the envisioned payloads into space. The group met with companies such as NPO Lavochkin and Kosmotras; however, according to Cantrell, Musk was seen as a novice and was consequently spat on by one of the Russian chief designers. The group returned to the United States empty-handed. In February 2002, the group returned to Russia to look for three ICBMs, bringing along Mike Griffin. Griffin had worked for the CIA's venture capital arm, In-Q-Tel, as well as NASA's Jet Propulsion Laboratory, and was just leaving Orbital Sciences, a maker of satellites and spacecraft. The group had another meeting with Kosmotras and were offered one rocket for US$8 million. Musk considered the price too high, and stormed out of the meeting. On the flight back from Moscow, Musk realized that he could start a company that could build the affordable rockets he needed. According to early Tesla and SpaceX investor Steve Jurvetson, Musk calculated that the raw materials for building a rocket were only 3 percent of the sales price of a rocket at the time. It was concluded that, in theory, by applying vertical integration and the modular approach employed in software engineering, SpaceX could cut launch price by a factor of ten and still enjoy a 70-percent gross margin. Ultimately, Musk ended up founding SpaceX with the long-term goal of creating a true spacefaring civilization.",
    ],
    [
      "Tesla",
      "Tesla, Inc. (originally Tesla Motors) was incorporated in July 2003 by Martin Eberhard and Marc Tarpenning, who financed the company until the Series A round of funding. Both men played active roles in the company's early development prior to Elon Musk's involvement. Musk led the Series A round of investment in February 2004, joining Tesla's board of directors as its chairman. All three, along with J. B. Straubel, were inspired by the earlier AC Propulsion tzero electric roadster prototype. Musk took an active role within the company and oversaw Roadster product design at a detailed level, but was not deeply involved in day-to-day business operations. Following the financial crisis in 2008 and after a series of escalating conflicts in 2007, Eberhard was ousted from the firm. Musk assumed leadership of the company as CEO and product architect in 2008, positions he still holds today. As of 2019, Elon Musk is the longest tenured CEO of any automotive manufacturer globally.                Tesla Motors first built an electric sports car, the Tesla Roadster, in 2008, with sales of about 2,500 vehicles to 31 countries. Tesla began delivery of its four-door Model S sedan on June 22, 2012. It unveiled its third product, the Model X, aimed at the SUV/minivan market, on February 9, 2012; however, the Model X launch was delayed until September 2015. In addition to its own cars, Tesla sold electric powertrain systems to Daimler for the Smart EV, Mercedes B-Class Electric Drive and Mercedes A Class, and to Toyota for the RAV4 EV. Musk was able to bring in both companies as long-term investors in Tesla.",
    ],
    [
      "OpenAI",
      'In December 2015, Musk announced the creation of OpenAI, a not-for-profit artificial intelligence (AI) research company. OpenAI aims to develop artificial general intelligence in a way that is safe and beneficial to humanity.                               By making AI available to everyone, OpenAI wants to "counteract large corporations who may gain too much power by owning super-intelligence systems devoted to profits, as well as governments which may use AI to gain power and even oppress their citizenry." Musk has stated he wants to counteract the concentration of power. In 2018 Musk left the OpenAI board to avoid possible future conflicts with his role as CEO of Tesla as Tesla increasingly became involved in AI through Tesla Autopilot.',
    ],
    [
      "Neuralink",
      "In 2016, Musk co-founded Neuralink, a neurotechnology startup company to integrate the human brain with artificial intelligence. The company is centered on creating devices that can be implanted in the human brain, with the eventual purpose of helping human beings merge with software and keep pace with advancements in artificial intelligence. These enhancements could improve memory or allow more direct interfacing with computing devices.",
    ],
    [
      "Philanthropy",
      "Musk is chairman of the Musk Foundation, which focuses its philanthropic efforts on providing solar-power energy systems in disaster areas as well as other goals. In 2010, the Musk Foundation collaborated with SolarCity to donate a 25 kW solar power system to the South Bay Community Alliance's hurricane response center in Coden, Alabama. In July 2011, the Musk Foundation donated US$250,000 towards a solar power project in Soma, Japan, a city that had been recently devastated by a tsunami.                               In July 2014, Musk was asked by cartoonist Matthew Inman and William Terbo, the grandnephew of Nikola Tesla, to donate US$8 million toward the construction of the Tesla Science Center at Wardenclyffe. Ultimately, Musk agreed to donate US$1 million toward the project and additionally pledged to build a Tesla Supercharger in the museum car park.                    In January 2015, Musk donated US$10 million to the Future of Life Institute to run a global research program aimed at keeping artificial intelligence beneficial to humanity.As of 2015, Musk is a trustee of the X Prize Foundation and a signatory of The Giving Pledge.In October 2018, in an effort to help solve the Flint water crisis, Musk and the Musk Foundation donated over $480,000 to install new water fountains with filtration systems for access to clean water at all Flint, Michigan schools. As of 2019, approximately 30,000 children in all 12 area schools have free, safe drinking water from the water filtration systems.      Musk has been a top donor for the ACLU.",
    ],
    [
      "Awards and recognition",
      "In 2006, Musk served as a member of the United States National Academy of Sciences Aeronautics and Space Engineering Board.                                  Inc. magazine Entrepreneur of the Year award for 2007 for his work on Tesla and SpaceX.                    2007 Index Design award for his design of the Tesla Roadster. Global Green 2006 product design award for his design of the Tesla Roadster, presented by Mikhail Gorbachev.                                            American Institute of Aeronautics and Astronautics George Low award for the most outstanding contribution in the field of space transportation in 2007/2008. Musk was recognized for his design of the Falcon 1, the first privately developed liquid-fuel rocket to reach orbit.                                            Listed as one of Time's 100 people who most affected the world in 2010.                                    The world governing body for aerospace records, Federation Aeronautique Internationale, presented Musk in 2010 with the highest award in air and space, the FAI Gold Space Medal, for designing the first privately developed rocket to reach orbit. Prior recipients include Neil Armstrong, Burt Rutan of Scaled Composites and John Glenn.                Named as one of the 75 most influential people of the 21st century by Esquire magazine.                     Recognized as a Living Legend of Aviation in 2010 by the Kitty Hawk Foundation for creating the successor to the Space Shuttle (Falcon 9 rocket and Dragon spacecraft).                       In 2012, Musk was awarded the Royal Aeronautical Society's highest award: a Gold Medal.                In 2013, Musk was named the Fortune Businessperson of the year for SpaceX, SolarCity, and Tesla.        Awarded the President's award for Exploration and Technology of the Explorers Club at the annual gala on March 16, 2014.                                       In 2015, he was awarded IEEE Honorary Membership.       In June 2016, Business Insider named Musk one of the \"Top 10 Business Visionaries Creating Value for the World\" along with Mark Zuckerberg and Sal Khan.      In December 2016, Musk was ranked 21st on Forbes list of The World's Most Powerful People.                  In May 2017, Musk was awarded the Oslo Business for Peace Award.                                         Musk was elected a Fellow of the Royal Society (FRS) in 2018.",
    ],
  ],
};
